# Generated by Django 6.0.6 on 2026-06-06 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Daily',
            new_name='Gradebook',
        ),
    ]
