# Generated by Django 5.2.5 on 2025-09-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughts',
            old_name='rating',
            new_name='ratting',
        ),
    ]
