# Generated by Django 5.2.8 on 2025-11-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_rating_thoughts_ratting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailys', to='school.users'),
        ),
    ]
