# Generated by Django 5.2.8 on 2025-11-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_daily_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.users'),
        ),
    ]
