# Generated by Django 6.0.6 on 2026-06-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_clas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gradebook',
            old_name='user',
            new_name='student',
        ),
    ]
