# Generated by Django 5.2.8 on 2025-12-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_daily_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tch_id', models.IntegerField(max_length=9)),
                ('name', models.CharField(max_length=123)),
                ('lt_name', models.CharField(max_length=123)),
                ('job', models.CharField(max_length=123)),
            ],
        ),
        migrations.RenameField(
            model_name='thoughts',
            old_name='ratting',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='users',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teachers'),
        ),
    ]
