# Generated by Django 6.0.6 on 2026-06-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_user_gradebook_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rating',
        ),
    ]
