# Generated by Django 5.2.8 on 2025-12-09 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teachers_rename_ratting_thoughts_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='tch_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
