# Generated by Django 6.0.6 on 2026-06-14 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_remove_comments_rating"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Teachers",
            new_name="Teacher",
        ),
        migrations.RenameField(
            model_name="class",
            old_name="cid",
            new_name="class_id",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="clas",
            new_name="class_name",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="lt_name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="tch_id",
            new_name="teacher_id",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(max_length=120)),
                ("text", models.TextField(max_length=255)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.student",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
